"""The two checked-in Mermaid diagrams, rendered from the code.

``docs/diagrams/event-flow.md`` and ``docs/diagrams/sagas.md`` are committed rather
than generated on demand: GitHub renders a Mermaid block in Markdown, so a reader
sees the architecture without running anything. That only works if the files are
*true*, which is why they are never hand-edited — :func:`render_diagrams` rebuilds
both from :mod:`plantkeeper.infrastructure.contracts.catalogue`, and
``tests/unit/docs/test_diagrams.py`` fails when the result differs from what is
committed.

The preambles live here rather than in ``tools/contracts.py`` because both the tool
and the test need them, and the test may not import the tool: ``tools/`` is a
directory of scripts, not an installed package.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Final

from plantkeeper.domain.base import DomainEvent
from plantkeeper.infrastructure.contracts.catalogue import (
    ProjectionLike,
    event_flow_diagram,
    saga_diagrams,
)

EVENT_FLOW_FILE: Final = "event-flow.md"
SAGA_DIAGRAMS_FILE: Final = "sagas.md"

EVENT_FLOW_PREAMBLE: Final = """# Event flow — generated

> **Generated by `make diagrams` (`tools/contracts.py`) — do not edit by hand.**
> The producer edges come from `EVENT_TOPICS` and the component that publishes each
> event; the consumer edges come from the saga, projection and write-side consumer
> registries. A test fails if this file and the code disagree.
>
> A consumer edge is drawn only when it crosses a bounded context: an event's own
> context consuming it is the default, and drawing every one of those would turn
> the diagram into a restatement of `docs/events.md`. The notes below the diagram
> say which events are consumed only inside their own context and which no
> consumer handles at all.

"""

SAGA_DIAGRAMS_PREAMBLE: Final = """# Orchestration sagas — generated

> **Generated by `make diagrams` (`tools/contracts.py`) — do not edit by hand.**
> Rendered by `python-cqrs`' own `SagaMermaid` from each saga's real step list, so
> the participants below are the step classes in the code. A test fails if this
> file and the code disagree.

"""


def render_diagrams[EventT: DomainEvent, HandlerT: object](
    diagrams_root: Path,
    projections: Iterable[ProjectionLike[EventT, HandlerT]] = (),
) -> dict[Path, str]:
    """Return each checked-in diagram file's full text, keyed by its path.

    ``projections`` is the read side's consumer list. The event-flow diagram is a
    statement about the *platform*, so a caller that can describe both consumer
    sets passes them: without the projections, every event only a read model
    consumes would be reported as consumed by nobody. The caller is
    ``python -m plantkeeper.admin.asyncapi``, the one process that has Django
    configured (``plantkeeper.infrastructure`` may not import it).
    """
    saga_blocks = "\n".join(
        f"## `{name}`\n\n```mermaid\n{body.rstrip()}\n```\n" for name, body in saga_diagrams()
    )
    return {
        diagrams_root / EVENT_FLOW_FILE: EVENT_FLOW_PREAMBLE + event_flow_diagram(projections),
        diagrams_root / SAGA_DIAGRAMS_FILE: SAGA_DIAGRAMS_PREAMBLE + saga_blocks,
    }
